### ISSUE TITLE
openstack-swift with OVH returns 401 Unauthorized

### ISSUE THREAD

**Issue by lrkwz** [gaul/s3proxy#323]
I'm using a swift bucket on OVH

The CLI tool `swift -A $OS_AUTH_URL -U $OS_USERNAME -K $OS_PASSWORD list -l foto-condivise` works smoothly.

My config is:

```yml
  s3proxy:
    image: andrewgaul/s3proxy
    ports:
    - 127.0.0.1:8084:80
    environment:
      S3PROXY_AUTHORIZATIONs: none
      JCLOUDS_PROVIDER: openstack-swift
      JCLOUDS_ENDPOINT: $OS_AUTH_URL
      JCLOUDS_REGION: $OS_REGION_NAME
      JCLOUDS_REGIONS: $OS_REGION_NAME
      #JCLOUDS_IDENTITY: $OS_TENANT_NAME:$OS_USERNAME
      JCLOUDS_IDENTITY: $OS_TENANT_ID:OS_USERNAME
      JCLOUDS_CREDENTIAL: $OS_PASSWORD
      JCLOUDS_KEYSTONE_VERSION: $OS_IDENTITY_API_VERSION
      JCLOUDS_KEYSTONE_SCOPE: project:Default
      JCLOUDS_KEYSTONE_PROJECT_DOMAIN_NAME: Default
```

(I've tried both versions of `JCLOUDS_IDENTITY`) the log states:

```
s3proxy_1    | [s3proxy] E 05-05 17:50:08.975 main org.gaul.s3proxy.Main:238 |::] Exception in thread "main" 
s3proxy_1    | [s3proxy] E 05-05 17:50:08.979 main org.gaul.s3proxy.Main:238 |::] org.jclouds.rest.AuthorizationException: request: POST https://auth.cloud.ovh.net/v3/auth/tokens HTTP/1.1  [Sensitive data in payload, use jclouds.wire.log.sensitive override to enable logging this data.] failed with response: HTTP/1.1 401 Unauthorized
s3proxy_1    | [s3proxy] E 05-05 17:50:08.979 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.openstack.swift.v1.handlers.SwiftErrorHandler.handleError(SwiftErrorHandler.java:51)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:138)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:107)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
s3proxy_1    | [s3proxy] E 05-05 17:50:08.980 main org.gaul.s3proxy.Main:238 |::] 	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
```
