### ISSUE TITLE
Public Read access does not work for bucket

### ISSUE THREAD

**Issue by alex-arica** [gaul/s3proxy#463]
I am using S3Proxy version 2.0.0 which is deployed in a Kubernetes locally with Kind.

I deployed the S3Proxy Docker container in Kubernetes with the following configuration:
```
spec:      
    containers:
      - image: andrewgaul/s3proxy:latest
        name: s3-test-service
        ports:
          - containerPort: 80
            protocol: TCP

        volumeMounts:
          - name: s3-test-service-pv
            mountPath: /data

        env:

          - name: JCLOUDS_REGIONS
            value: "UK"

          - name: JCLOUDS_PROVIDER
            value: "filesystem"

          - name: JCLOUDS_FILESYSTEM_BASEDIR
            value: "/data"

          - name: S3PROXY_IDENTITY
            valueFrom:
              secretKeyRef:
                name: s3-test-service
                key: s3ApiAccessKey

          - name: S3PROXY_CREDENTIAL
            valueFrom:
              secretKeyRef:
                name: s3-test-service
                key: s3ApiSecretKey

```

I have a server-side Java application which creates a bucket "photos" which is publicly accessible, as follows:

```
final EndpointConfiguration endpointConf = new EndpointConfiguration(conf.getS3Endpoint(), conf.getS3Region());
final AWSCredentials credentials = new BasicAWSCredentials(conf.getS3ApiAccessKey(), conf.getS3ApiSecretKey());

final AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder
        .standard()
        .withPathStyleAccessEnabled(true)
        .withEndpointConfiguration(endpointConf)
        .withCredentials(new AWSStaticCredentialsProvider(credentials));

s3client = s3ClientBuilder.build();

final CreateBucketRequest createBucketRequest = new CreateBucketRequest("photos")
                                               .withCannedAcl(CannedAccessControlList.PublicRead);
s3client.createBucket(createBucketRequest);
```

The same Java app uploads a photo to the bucket "photos" to the following path:
```
medium/1.jpeg
```

I can see the photo in the s3proxy data folder. So far so good.

I configured Ingress to expose S3Proxy Docker container via the hostname:
```
http://s3-test-service.localhost
```

When I try to access to the photo via my browser:
```
http://s3-test-service.localhost/photos/medium/1.jpeg
```

I get this error:
```<Error>
<Code>AccessDenied</Code>
<Message>Forbidden</Message>
<RequestId>4442587FB7D0A2F9</RequestId>
</Error>
```
I cannot access to the photo publicly.
However, it works if I disable credentials with:
```
- name: S3PROXY_AUTHORIZATION
  value: none
```

Did I miss a configuration allowing me to set the bucket with public read access?
