### ISSUE TITLE
Adding --properties arguments when running docker image

### ISSUE THREAD

**Issue by pancochea** [gaul/s3proxy#663]
We want to add arguments to add two properties files to s3, locally, we run it this way:

`s3proxy --properties "/etc/s3proxy/file1" --properties "/etc/s3proxy/file2"`

Now we want to run it in kubernetes, so we created a deployment and added args to the pod:

```
spec:
  containers:
    - args:
        - '--properties'
        - /etc/s3proxy/file1
        - '--properties'
        - /etc/s3proxy/file2
``` 

But the properties are not being loaded. After checking the dockerfile and the script, I can see that arguments are not being passed to the exec command, so it's not going to load those arguments.

Is there a way to load those properties, or we will have to custom build s3proxy?

Also, we don't understand the --properties /dev/null at the end of the exec.
