### ISSUE TITLE
Region regression/bug around the openstack-swift provider

### ISSUE THREAD

**Issue by tristanveness** [gaul/s3proxy#824]
Hi

Awesome project BTW. Fantastic work.

Just wanted to report a regression I found whilst trying to connect the s3proxy to an in-house swift cluster using keystone v2

I have managed to get it to work successfully on an older version of s3proxy

docker-compose.yaml
```
version: '3.8'

services:
  s3proxy:
    image: andrewgaul/s3proxy:travis-1232
    container_name: s3proxy
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    environment:
      S3PROXY_AUTHORIZATION: "none" 
      JCLOUDS_PROVIDER: "openstack-swift"
      JCLOUDS_ENDPOINT: "http://****/v2.0"
      JCLOUDS_REGION: "regionOne"
      JCLOUDS_IDENTITY: "*****:*****"
      JCLOUDS_CREDENTIAL: "*****"
      JCLOUDS_KEYSTONE_VERSION: "2"
```

Validated success with rclone
```
[s3-to-swift]
type = s3
provider = Other
endpoint = http://127.0.0.1:8080
access_key_id =
secret_access_key =
```

When changing to:
```
image: andrewgaul/s3proxy:travis-1236
```

It fails to start with:
```
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] Exception in thread "main" 
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] java.lang.IllegalArgumentException: region regionOne not in []
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.checkRegionId(RegionScopedBlobStoreContext.java:88)
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.getBlobStore(RegionScopedBlobStoreContext.java:72)
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.getBlobStore(RegionScopedBlobStoreContext.java:122)
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at org.gaul.s3proxy.Main.createBlobStore(Main.java:313)
s3proxy  | [s3proxy] E 06-06 03:07:11.640 main org.gaul.s3proxy.Main:236 |::] 	at org.gaul.s3proxy.Main.main(Main.java:112)
```

I noticed that there were some behavioural changes mentioned around regions in: https://github.com/gaul/s3proxy/issues/81 that might coincide with travis-1232 and travis-1236

I attempted to set ` JCLOUDS_REGIONS` as well as per some other threads, but the result was the same, `region *** not in []`
